### ISSUE TITLE
大佬，你boxjs里没有可以填滴滴token的地方呀？

### ISSUE THREAD

**Issue by LevineWoo** [passerby-b/didi_fruit#1]
boxjs直接就没有滴滴这个项目呃。。

**Comment by passerby-b** [comment]
订阅地址不对,进tg群看置顶消息

**Comment by nwsuafzq** [comment]
没法浇水成功呢

**Comment by moxinshi** [comment]
只有stream是不是不行？得用圈x？boxjs是个啥。。。用stream抓了好多access-token都不一样

**Comment by happyskey** [comment]
大佬nodejs建议专门弄个文件填账号token，不然没法自动更新，就像京东到家那样。

**Comment by ryan016** [comment]
圈x里，重写地址与类型填好了，但用于匹配的body与替换应如何填写？谢谢！
