### ISSUE TITLE
滴滴果园收水桶的脚本总提示cookie过期

### ISSUE THREAD

**Issue by XuuKoo** [passerby-b/didi_fruit#10]
ios上用小火箭跑的脚本。
用的仓库内的脚本抓的cookie，dd_fruit运行正常，但是收水桶的脚本总提示cookie过期。
![image](https://user-images.githubusercontent.com/61222909/129170521-e7fa6fbf-733f-4217-9220-440de6fdb90d.jpeg)

**Comment by lovelyelfpop** [comment]
应该是没判断好cookie过期的错误码
{ errmsg:'user invalid', errno:100 } 这个是没有获取到用户的错误码
