### ISSUE TITLE
从任务中心进滴滴果园可以得到20g水滴，能否增加一下这项

### ISSUE THREAD

**Issue by lxr760** [passerby-b/didi_fruit#19]
好久不更新了   

能否把这个任务加一下

另外，关注公众号也可以得到水滴，脚本能实现不

**Comment by passerby-b** [comment]
放弃治疗了,水果成熟太慢了,我的几个号都黑了,没果园了

**Comment by lxr760** [comment]
> 放弃治疗了,水果成熟太慢了,我的几个号都黑了,没果园了

那我黑号黑的还不算严重   只是福利中心进不去   其他任务正常能做

水果现在貌似要9个多月才能好  是有点慢
