### ISSUE TITLE
百度果园，高德果园，粑粑农场(淘宝和支付宝)，饿了么果园(支付宝和饿了么) 

### ISSUE THREAD

**Issue by lovelyelfpop** [passerby-b/didi_fruit#7]
大佬能不能研究下？

**Comment by passerby-b** [comment]
没戏

**Comment by lovelyelfpop** [comment]
https://lztzhk.smartapps.baidu.com/pages/index/index?shareToken=&idfrom=

**Comment by lovelyelfpop** [comment]
https://lztzhk.smartapps.baidu.com/pages/index/index?shareToken=&idfrom=
这是百度果园的js版，主要就是个请求的sign，算法在里面

下面是百度果园的百度小程序源码包，和网页版内容一样，sign 算法在 app.js 里面
[SuUusWn6HcegDP5SRN06mC8wF9arysFi.zip](https://github.com/passerby-b/didi_fruit/files/6905982/SuUusWn6HcegDP5SRN06mC8wF9arysFi.zip)

**Comment by passerby-b** [comment]
实际百度的我已经写出来了,但是容易黑号就没公布

**Comment by lovelyelfpop** [comment]
大佬牛逼

**Comment by happysoul** [comment]
抓了好几个app的农场、小游戏、签到，发现几乎没有get/post ，只有connect，是不是这类请求没戏了？（网页桥接原生接口然后走tcp？）
Mei团 的偶尔会有个post数据，发现body还是个二进制的包，大多数都是connect 
其他的有 一折、头条、拼DD 也都是很少有post，还有几个平台更绝，全文加密，甚至还有防代理。。。
只有JD头铁用h5

**Comment by lovelyelfpop** [comment]
我每个app都抓到包了。
淘宝 安卓端要使用xposed模块hook SPDY协议，使其能够被抓包 https://blog.csdn.net/zhangmiaoping23/article/details/105827285

有些app可能用的 HTTP/2，fiddler抓不到，但是手机端HttpCanary可以抓。


有的app抓到包也没用，有验证参数签名的，比如淘宝系所有app（包括高德和饿了么），还有一折特卖也有参数签名
