### ISSUE TITLE
今日头条极速版的果园能弄个不？

### ISSUE THREAD

**Issue by lovelyelfpop** [passerby-b/didi_fruit#8]

**Comment by passerby-b** [comment]
入口在哪里?

**Comment by lovelyelfpop** [comment]
今日头条极速版-下面底栏中间“任务”-免费领水果

**Comment by passerby-b** [comment]
见了鬼,我的没有

**Comment by lovelyelfpop** [comment]
我是安卓，你是ios？

**Comment by lovelyelfpop** [comment]
给你个口令 你看看能不能进去
```
9 .0f:/腹݄制€8KMvpP€YDxgk€打开今日头条极速版💧可以帮我浇浇水嘛？
```

**Comment by happysoul** [comment]
头条的我好像抓过，记得是post二进制数据，另外好像还有加密。。。

**Comment by lovelyelfpop** [comment]
@happysoul  是普通的 https 请求

**Comment by happysoul** [comment]
找不到果园了，找到的只有种菜给金币的
只看了一个请求 里面一堆token csrf xx-token 看完直接弃坑了

**Comment by lovelyelfpop** [comment]
好像只有部分用户开放了果园，或者可能是安卓才有果园。

我之前找到一个 jrtt.js 可以 签到，睡觉，三餐补贴 和 农场种菜。
[jrtt.zip](https://github.com/passerby-b/didi_fruit/files/6967580/jrtt.zip)

但是这个脚本不支持看视频领取翻倍那种任务，应该是需要 时间戳和验证签名

果园应该类似

**Comment by happysoul** [comment]
可以确认的是 安卓才有浇水得水果（别人的安卓手机折腾了将近1年才得了一箱水果），ios只有一个普通的金币果园做任务还不如看1个广告给的积分多，睡觉什么的给的积分也很少不如15秒广告
脚本看了 循着地址也找到原作者的git，不过这个需要配置的参数太多了，而且也没提供具体抓取位置等信息，就没再折腾了
